### ISSUE TITLE
Error on ingest in logs alongside success -> no intersection on query

### ISSUE THREAD

**Issue by jlaura** [stac-utils/stac-server#103]
I have the following STAC.json file. This file shows valid using the validator for the core spec. I do get an error on the projection extension, presumably because this is not a terrestrial datum (see the unknowns in the wkt2 and projjson strings)

The STAC file:
<details>
2021-07-12T14:53:28.411Z	c9db0784-9f76-5856-ac23-5ee2c6eb7e2b	DEBUG	Data: {
    "type": "Feature",
    "stac_version": "1.0.0-beta.2",
    "id": "F03_036840_1811_XN_01N221W__F01_035996_1811_XN_01N221W_DEM",
    "properties": {
        "title": "Ames Stereo Pipeline Derived 20mpp Content Camera DTM and Ortho Image; Mars; F03_036840_1811_XN_01N221W, F01_035996_1811_XN_01N221W",
        "description": "This is a digital terrain model (DTM) extracted from Context Camera (CTX) stereo images from the Mars Reconnaissance Orbiter mission. This data product is a DTM from stereo images acquired at approximately 6 meters/pixel resolution, which allows an output DTM resolution of 20 meters/pixel. The DTM was generated using the Ames Stereo Pipeline software (https://github.com/NeoGeographyToolkit/StereoPipeline)and using automated methods.This DTM was generated for general and public use, including scientific and engineering purposes. This DTM also serves as a foundation for ortho-projection.",
        "mission": "Mars Reconnaissance Orbiter",
        "instruments": [
            "Context Camera (CTX)"
        ],
        "gsd": 20,
        "license": "PDDL-1.0",
        "proj:epsg": 49900,
        "proj:wkt2": "\"PROJCS[\\\"unnamed\\\",GEOGCS[\\\"D_MARS\\\",DATUM[\\\"D_MARS\\\",SPHEROID[\\\"MARS\\\",3396000,0]],PRIMEM[\\\"Reference Meridian\\\",0],UNIT[\\\"degree\\\",0.0174532925199433,AUTHORITY[\\\"EPSG\\\",\\\"9122\\\"]]],PROJECTION[\\\"Orthographic\\\"],PARAMETER[\\\"latitude_of_origin\\\",1.1511],PARAMETER[\\\"central_meridian\\\",138.267],PARAMETER[\\\"false_easting\\\",0],PARAMETER[\\\"false_northing\\\",0],UNIT[\\\"metre\\\",1,AUTHORITY[\\\"EPSG\\\",\\\"9001\\\"]],AXIS[\\\"Easting\\\",EAST],AXIS[\\\"Northing\\\",NORTH]]\"",
        "proj:projjson": {
            "$schema": "https://proj.org/schemas/v0.2/projjson.schema.json",
            "type": "ProjectedCRS",
            "name": "unknown",
            "base_crs": {
                "name": "unknown",
                "datum": {
                    "type": "GeodeticReferenceFrame",
                    "name": "unknown",
                    "ellipsoid": {
                        "name": "unknown",
                        "radius": 3396000
                    },
                    "prime_meridian": {
                        "name": "Reference meridian",
                        "longitude": 0
                    }
                },
                "coordinate_system": {
                    "subtype": "ellipsoidal",
                    "axis": [
                        {
                            "name": "Longitude",
                            "abbreviation": "lon",
                            "direction": "east",
                            "unit": "degree"
                        },
                        {
                            "name": "Latitude",
                            "abbreviation": "lat",
                            "direction": "north",
                            "unit": "degree"
                        }
                    ]
                }
            },
            "conversion": {
                "name": "unknown",
                "method": {
                    "name": "Orthographic",
                    "id": {
                        "authority": "EPSG",
                        "code": 9840
                    }
                },
                "parameters": [
                    {
                        "name": "Latitude of natural origin",
                        "value": 1.1511,
                        "unit": "degree",
                        "id": {
                            "authority": "EPSG",
                            "code": 8801
                        }
                    },
                    {
                        "name": "Longitude of natural origin",
                        "value": 138.267,
                        "unit": "degree",
                        "id": {
                            "authority": "EPSG",
                            "code": 8802
                        }
                    },
                    {
                        "name": "False easting",
                        "value": 0,
                        "unit": "metre",
                        "id": {
                            "authority": "EPSG",
                            "code": 8806
                        }
                    },
                    {
                        "name": "False northing",
                        "value": 0,
                        "unit": "metre",
                        "id": {
                            "authority": "EPSG",
                            "code": 8807
                        }
                    }
                ]
            },
            "coordinate_system": {
                "subtype": "Cartesian",
                "axis": [
                    {
                        "name": "Easting",
                        "abbreviation": "E",
                        "direction": "east",
                        "unit": "metre"
                    },
                    {
                        "name": "Northing",
                        "abbreviation": "N",
                        "direction": "north",
                        "unit": "metre"
                    }
                ]
            }
        },
        "proj:bbox": [
            137.719169342824,
            -1.49251086136152,
            138.817006100134,
            3.7553673288675
        ],
        "proj:centroid": {
            "lat": 1.13142823375299,
            "lon": 138.268087721479
        },
        "proj:shape": [
            15535,
            3243
        ],
        "proj:transform": [
            -32290,
            20,
            0,
            154230,
            0,
            -20
        ],
        "cube:dimensions": {
            "x": {
                "type": "spatial",
                "axis": "x",
                "extent": [
                    137.719169342824,
                    138.817006100134
                ]
            },
            "y": {
                "type": "spatial",
                "axis": "y",
                "extent": [
                    -1.49251086136152,
                    3.7553673288675
                ]
            }
        },
        "datetime": "2021-01-01T00:00:00Z"
    },
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [
                    137.719169342824,
                    -1.49251086136152
                ],
                [
                    137.719169342824,
                    3.7553673288675
                ],
                [
                    138.817006100134,
                    3.7553673288675
                ],
                [
                    138.817006100134,
                    -1.49251086136152
                ],
                [
                    137.719169342824,
                    -1.49251086136152
                ]
            ]
        ]
    },
    "links": [
        {
            "rel": "self",
            "href": "https://asc-mars.s3-us-west-2.amazonaws.com/ctx_dtms/F03_036840_1811_XN_01N221W__F01_035996_1811_XN_01N221W/F03_036840_1811_XN_01N221W__F01_035996_1811_XN_01N221W_DEM.json",
            "type": "application/json"
        },
        {
            "rel": "parent",
            "href": "https://asc-mars.s3.us-west-2.amazonaws.com/ctx_dtms/collection.json",
            "type": "application/json"
        },
        {
            "rel": "root",
            "href": "https://asc-mars.s3.us-west-2.amazonaws.com/catalog.json",
            "type": "application/json"
        },
        {
            "rel": "collection",
            "href": "https://asc-mars.s3.us-west-2.amazonaws.com/ctx_dtms/collection.json",
            "type": "application/json"
        }
    ],
    "assets": {
        "thumbnail": {
            "href": "https://asc-mars.s3-us-west-2.amazonaws.com/ctx_dtms/F03_036840_1811_XN_01N221W__F01_035996_1811_XN_01N221W/F03_036840_1811_XN_01N221W__F01_035996_1811_XN_01N221W_DEM.jpg",
            "type": "image/jpeg",
            "title": "DEM Thumbnail",
            "key": "thumbnail",
            "roles": [
                "thumbnail"
            ]
        },
        "dem": {
            "href": "https://asc-mars.s3-us-west-2.amazonaws.com/ctx_dtms/F03_036840_1811_XN_01N221W__F01_035996_1811_XN_01N221W/F03_036840_1811_XN_01N221W__F01_035996_1811_XN_01N221W_DEM.tif",
            "type": "image/tiff; application=geotiff; profile=cloud-optimized",
            "title": "DEM",
            "key": "dem",
            "roles": [
                "data"
            ]
        },
        "hillshade": {
            "href": "https://asc-mars.s3-us-west-2.amazonaws.com/ctx_dtms/F03_036840_1811_XN_01N221W__F01_035996_1811_XN_01N221W/F03_036840_1811_XN_01N221W__F01_035996_1811_XN_01N221W_HILLSHADE.tif",
            "type": "image/tiff; application=geotiff; profile=cloud-optimized",
            "title": "Hillshade",
            "key": "hillshade",
            "roles": [
                "data"
            ]
        },
        "ortho image": {
            "href": "https://asc-mars.s3-us-west-2.amazonaws.com/ctx_dtms/F03_036840_1811_XN_01N221W__F01_035996_1811_XN_01N221W/F03_036840_1811_XN_01N221W__F01_035996_1811_XN_01N221W_ORTHO.tif",
            "type": "image/tiff; application=geotiff; profile=cloud-optimized",
            "title": "Orthoimage",
            "key": "ortho image",
            "roles": [
                "data"
            ]
        },
        "fgdc_metadata": {
            "href": "https://asc-mars.s3-us-west-2.amazonaws.com/ctx_dtms/F03_036840_1811_XN_01N221W__F01_035996_1811_XN_01N221W/F03_036840_1811_XN_01N221W__F01_035996_1811_XN_01N221W_DEM.xml",
            "type": "application/xml",
            "title": "FGDC Metadata",
            "key": "fgdc_metadata",
            "roles": [
                "metadata"
            ]
        },
        "qa_metric": {
            "href": "https://asc-mars.s3-us-west-2.amazonaws.com/ctx_dtms/F03_036840_1811_XN_01N221W__F01_035996_1811_XN_01N221W/qa_metrics.txt",
            "type": "text/plain",
            "title": "Quality Assurance Metrics",
            "key": "qa_metric",
            "roles": [
                "metadata"
            ]
        },
        "intersection_err": {
            "href": "https://asc-mars.s3-us-west-2.amazonaws.com/ctx_dtms/F03_036840_1811_XN_01N221W__F01_035996_1811_XN_01N221W/F03_036840_1811_XN_01N221W__F01_035996_1811_XN_01N221W_IntersectionErr.tif",
            "type": "image/tiff; application=geotiff",
            "title": "ASP generated intersection error raster",
            "key": "intersection_err",
            "roles": [
                "metadata",
                "data-mask"
            ]
        },
        "provenance": {
            "href": "https://asc-mars.s3-us-west-2.amazonaws.com/ctx_dtms/F03_036840_1811_XN_01N221W__F01_035996_1811_XN_01N221W/provenance.txt",
            "type": "text/plain",
            "title": "Processing steps in ISIS and ASP used to generate the data product",
            "key": "provenance",
            "roles": [
                "metadata"
            ]
        }
    },
    "bbox": [
        137.719169342824,
        -1.49251086136152,
        138.817006100134,
        3.7553673288675
    ],
    "stac_extensions": [
        "projection",
        "datacube"
    ],
    "collection": "ctx_dtms"
}
</details>

On ingest, I am seeing the following in my cloud watch logs:

```
2021-07-12T14:53:28.661Z	c9db0784-9f76-5856-ac23-5ee2c6eb7e2b	ERROR	ResponseError: illegal_argument_exception
    at onBody (/var/task/index.js:16554:23)
    at IncomingMessage.onEnd (/var/task/index.js:16481:11)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  meta: {
    body: { error: [Object], status: 400 },
    statusCode: 400,
    headers: {
      date: 'Mon, 12 Jul 2021 14:53:28 GMT',
      'content-type': 'application/json; charset=UTF-8',
      'content-length': '351',
      connection: 'keep-alive',
      'access-control-allow-origin': '*'
    },
    meta: {
      context: null,
      request: [Object],
      name: 'elasticsearch-js',
      connection: [Object],
      attempts: 0,
      aborted: false
    }
  }
}
```
 Followed immediately by:

```INFO	Ingested 1 Items: [THE ABOVE STAC FILE]```

When I query using a bbox (sat-search), I am not seeing any results. This makes sense, because checking the indices, I can see that the associated collection has been created and that the item index has been created. The count on that index is zero though. I wonder what I might be missing in the error message?

**Comment by jlaura** [comment]
So, I figured this out as well. I had to remove both the proj and the data cube extensions from the stac item. Then ES ingest work without an issue. I'll dig through the docs on this repo to see how best to get extensions added back in so that ES supports them. 

I suspect the issue is that the index is not correct inside ES.

**Comment by demiurg** [comment]
It depends on the mapping. For a proj:centroid, we want geo_point mapping, but for other STAC attributes, we rely on ES dynamic mapping. This is interesting, because I thought proj:epsg should be a string, and doesn't need a special type. I think the thing to do here is to figure what ES data type and  STAC JSON payload record did no align to generate an error.

**Comment by jlaura** [comment]
I am still working on this. I was able to get one of my data sets to ingest by writing to the sqs queue (and skipping the sns). Here is the STAC file:

<details>

```json
 {
    "type": "Feature",
    "stac_version": "1.0.0",
    "id": "D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W_DEM",
    "properties": {
        "title": "Ames Stereo Pipeline Derived 20mpp Content Camera DTM and Ortho Image; Mars; D18_034426_1877_XN_07N196W, D17_033793_1865_XN_06N196W",
        "description": "This is a digital terrain model (DTM) extracted from Context Camera (CTX) stereo images from the Mars Reconnaissance Orbiter mission. This data product is a DTM from stereo images acquired at approximately 6 meters/pixel resolution, which allows an output DTM resolution of 20 meters/pixel. The DTM was generated using the Ames Stereo Pipeline software (https://github.com/NeoGeographyToolkit/StereoPipeline)and using automated methods. This DTM was generated for general and public use, including scientific and engineering purposes. This DTM also serves as a foundation for ortho-projection.",
        "mission": "Mars Reconnaissance Orbiter",
        "instruments": [
            "Context Camera (CTX)"
        ],
        "gsd": 20,
        "license": "PDDL-1.0",
        "proj:epsg": 49900,
        "proj:wkt2": "\"PROJCS[\\\"unnamed\\\",GEOGCS[\\\"D_MARS\\\",DATUM[\\\"D_MARS\\\",SPHEROID[\\\"MARS\\\",3396000,0]],PRIMEM[\\\"Reference Meridian\\\",0],UNIT[\\\"degree\\\",0.0174532925199433,AUTHORITY[\\\"EPSG\\\",\\\"9122\\\"]]],PROJECTION[\\\"Orthographic\\\"],PARAMETER[\\\"latitude_of_origin\\\",7.61971],PARAMETER[\\\"central_meridian\\\",163.679],PARAMETER[\\\"false_easting\\\",0],PARAMETER[\\\"false_northing\\\",0],UNIT[\\\"metre\\\",1,AUTHORITY[\\\"EPSG\\\",\\\"9001\\\"]],AXIS[\\\"Easting\\\",EAST],AXIS[\\\"Northing\\\",NORTH]]\"",
        "proj:projjson": {
            "$schema": "https://proj.org/schemas/v0.2/projjson.schema.json",
            "type": "ProjectedCRS",
            "name": "unknown",
            "base_crs": {
                "name": "unknown",
                "datum": {
                    "type": "GeodeticReferenceFrame",
                    "name": "unknown",
                    "ellipsoid": {
                        "name": "unknown",
                        "radius": 3396000
                    },
                    "prime_meridian": {
                        "name": "Reference meridian",
                        "longitude": 0
                    }
                },
                "coordinate_system": {
                    "subtype": "ellipsoidal",
                    "axis": [
                        {
                            "name": "Longitude",
                            "abbreviation": "lon",
                            "direction": "east",
                            "unit": "degree"
                        },
                        {
                            "name": "Latitude",
                            "abbreviation": "lat",
                            "direction": "north",
                            "unit": "degree"
                        }
                    ]
                }
            },
            "conversion": {
                "name": "unknown",
                "method": {
                    "name": "Orthographic",
                    "id": {
                        "authority": "EPSG",
                        "code": 9840
                    }
                },
                "parameters": [
                    {
                        "name": "Latitude of natural origin",
                        "value": 7.61971,
                        "unit": "degree",
                        "id": {
                            "authority": "EPSG",
                            "code": 8801
                        }
                    },
                    {
                        "name": "Longitude of natural origin",
                        "value": 163.679,
                        "unit": "degree",
                        "id": {
                            "authority": "EPSG",
                            "code": 8802
                        }
                    },
                    {
                        "name": "False easting",
                        "value": 0,
                        "unit": "metre",
                        "id": {
                            "authority": "EPSG",
                            "code": 8806
                        }
                    },
                    {
                        "name": "False northing",
                        "value": 0,
                        "unit": "metre",
                        "id": {
                            "authority": "EPSG",
                            "code": 8807
                        }
                    }
                ]
            },
            "coordinate_system": {
                "subtype": "Cartesian",
                "axis": [
                    {
                        "name": "Easting",
                        "abbreviation": "E",
                        "direction": "east",
                        "unit": "metre"
                    },
                    {
                        "name": "Northing",
                        "abbreviation": "N",
                        "direction": "north",
                        "unit": "metre"
                    }
                ]
            }
        },
        "proj:bbox": [
            163.412121713001,
            7.31411901028742,
            163.94688769192,
            7.92600146373682
        ],
        "proj:centroid": {
            "lat": 7.62006023701212,
            "lon": 163.67950470246052
        },
        "proj:shape": [
            1801,
            1561
        ],
        "proj:transform": [
            -15570,
            20,
            0,
            18070,
            0,
            -20
        ],
        "cube:dimensions": {
            "x": {
                "type": "spatial",
                "axis": "x",
                "extent": [
                    163.412121713001,
                    163.94688769192
                ]
            },
            "y": {
                "type": "spatial",
                "axis": "y",
                "extent": [
                    7.31411901028742,
                    7.92600146373682
                ]
            }
        },
        "ssys:targets": [
            "Mars"
        ],
        "datetime": "2021-01-01T00:00:00Z"
    },
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [
                    163.412121713001,
                    7.31411901028742
                ],
                [
                    163.412121713001,
                    7.92600146373682
                ],
                [
                    163.94688769192,
                    7.92600146373682
                ],
                [
                    163.94688769192,
                    7.31411901028742
                ],
                [
                    163.412121713001,
                    7.31411901028742
                ]
            ]
        ]
    },
    "links": [
        {
            "rel": "self",
            "href": "https://asc-mars.s3-us-west-2.amazonaws.com/ctx_dtms/D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W/D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W_DEM.json",
            "type": "application/json"
        },
        {
            "rel": "parent",
            "href": "https://asc-mars.s3.us-west-2.amazonaws.com/ctx_dtms/collection.json",
            "type": "application/json"
        },
        {
            "rel": "root",
            "href": "https://asc-mars.s3.us-west-2.amazonaws.com/catalog.json",
            "type": "application/json"
        },
        {
            "rel": "collection",
            "href": "https://asc-mars.s3.us-west-2.amazonaws.com/ctx_dtms/collection.json",
            "type": "application/json"
        }
    ],
    "assets": {
        "thumbnail": {
            "href": "https://asc-mars.s3-us-west-2.amazonaws.com/ctx_dtms/D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W/D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W_DEM.jpg",
            "type": "image/jpeg",
            "title": "DEM Thumbnail",
            "key": "thumbnail",
            "roles": [
                "thumbnail"
            ]
        },
        "dem": {
            "href": "https://asc-mars.s3-us-west-2.amazonaws.com/ctx_dtms/D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W/D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W_DEM.tif",
            "type": "image/tiff; application=geotiff; profile=cloud-optimized",
            "title": "DEM",
            "key": "dem",
            "roles": [
                "data"
            ]
        },
        "hillshade": {
            "href": "https://asc-mars.s3-us-west-2.amazonaws.com/ctx_dtms/D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W/D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W_HILLSHADE.tif",
            "type": "image/tiff; application=geotiff; profile=cloud-optimized",
            "title": "Hillshade",
            "key": "hillshade",
            "roles": [
                "data"
            ]
        },
        "ortho image": {
            "href": "https://asc-mars.s3-us-west-2.amazonaws.com/ctx_dtms/D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W/D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W_ORTHO.tif",
            "type": "image/tiff; application=geotiff; profile=cloud-optimized",
            "title": "Orthoimage",
            "key": "ortho image",
            "roles": [
                "data"
            ]
        },
        "fgdc_metadata": {
            "href": "https://asc-mars.s3-us-west-2.amazonaws.com/ctx_dtms/D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W/D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W_DEM.xml",
            "type": "application/xml",
            "title": "FGDC Metadata",
            "key": "fgdc_metadata",
            "roles": [
                "metadata"
            ]
        },
        "qa_metric": {
            "href": "https://asc-mars.s3-us-west-2.amazonaws.com/ctx_dtms/D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W/qa_metrics.txt",
            "type": "text/plain",
            "title": "Quality Assurance Metrics",
            "key": "qa_metric",
            "roles": [
                "metadata"
            ]
        },
        "intersection_err": {
            "href": "https://asc-mars.s3-us-west-2.amazonaws.com/ctx_dtms/D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W/D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W_IntersectionErr.tif",
            "type": "image/tiff; application=geotiff",
            "title": "ASP generated intersection error raster",
            "key": "intersection_err",
            "roles": [
                "metadata",
                "data-mask"
            ]
        },
        "provenance": {
            "href": "https://asc-mars.s3-us-west-2.amazonaws.com/ctx_dtms/D18_034426_1877_XN_07N196W__D17_033793_1865_XN_06N196W/provenance.txt",
            "type": "text/plain",
            "title": "Processing steps in ISIS and ASP used to generate the data product",
            "key": "provenance",
            "roles": [
                "metadata"
            ]
        }
    },
    "bbox": [
        163.412121713001,
        7.31411901028742,
        163.94688769192,
        7.92600146373682
    ],
    "stac_extensions": [
        "https://stac-extensions.github.io/projection/v1.0.0/schema.json",
        "https://stac-extensions.github.io/datacube/v1.0.0/schema.json"
    ],
    "collection": "ctx_dtms"
}
```
</details>

as printed from the debug in the ingest-stac lambda logs.

The exception that I am seeing is:

```
2021-07-22T14:22:14.353Z	5a02238c-18e9-5240-be42-7aff99a56506	ERROR	ResponseError: illegal_argument_exception
    at onBody (/var/task/index.js:16554:23)
    at IncomingMessage.onEnd (/var/task/index.js:16481:11)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  meta: {
    body: { error: [Object], status: 400 },
    statusCode: 400,
    headers: {
      date: 'Thu, 22 Jul 2021 14:22:14 GMT',
      'content-type': 'application/json; charset=UTF-8',
      'content-length': '351',
      connection: 'keep-alive',
      'access-control-allow-origin': '*'
    },
    meta: {
      context: null,
      request: [Object],
      name: 'elasticsearch-js',
      connection: [Object],
      attempts: 0,
      aborted: false
    }
  }
}
```

I have tried this two ways: (1) I created an index by passing the collection into the ingest-stac lambda. That results in a collection being created, but the mapping is a default (e.g., it has `eo:*` elements when my stac files do not use the `eo` extension. I also tried creating an empty index (e.g., `PUT ctx_dtms`) without a mapping. I am then passing the above message to the ingest SQS queue (because pushing to the SNS is not working).

The STAC file above, is valid as per the staclint web app. I am not seeing any other logs (the dead letter queue is empty). 

Two questions right now: (1) when the README says to ingest the collection first, what specifically does that mean? Pass in a full mapping to the ingest endpoint? pass in the collection.json to the endpoint? Use some API to create an empty index? and (2) any suggestions how to start debugging the above error? the illegal_response_exception is from the ES side of the stack, but the JSON is valid and the index does not have an existing mapping.

Thanks again for any support!

**Comment by jlaura** [comment]
I have set up logging on the ES side and am not seeing any errors being posted from ES. The only information I am getting is the 400 response and the illegal_argument_exception. It is not clear to me why one STAC file would ingest without issue while another is throwing this issue.

**Comment by jlaura** [comment]
I have found the specific problem, so will open a new issue describing how to reproduce.
