### ISSUE TITLE
ES Ingest Failure w/ PROJJSON string

### ISSUE THREAD

**Issue by jlaura** [stac-utils/stac-server#108]
This issue spawned out of issue #103, where ingest was failing with an `illegal_argument_exception`. The index has been created, but is empty (no mapping). This error throws in the CloudWatch logs when the ingest lambda attempts an insert.

<details>
<summary>Error Message</summary>

```
ERROR	ResponseError: illegal_argument_exception
    at onBody (/var/task/index.js:16554:23)
    at IncomingMessage.onEnd (/var/task/index.js:16481:11)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  meta: {
    body: { error: [Object], status: 400 },
    statusCode: 400,
    headers: {
      date: 'Tue, 27 Jul 2021 14:01:31 GMT',
      'content-type': 'application/json; charset=UTF-8',
      'content-length': '351',
      connection: 'keep-alive',
      'access-control-allow-origin': '*'
    },
    meta: {
      context: null,
      request: [Object],
      name: 'elasticsearch-js',
      connection: [Object],
      attempts: 0,
      aborted: false
    }
  }
}
```

</details>

I have narrowed the error down to something in the following PROJJSON on ingest. The error is thrown (in index.json) when the PROJJSON string is:

<details>
<summary>Failing PROJJSON w/ orthographic projection</summary>

```"proj:projjson": {
            "$schema": "https://proj.org/schemas/v0.2/projjson.schema.json",
            "type": "ProjectedCRS",
            "name": "unknown",
            "base_crs": {
                "name": "unknown",
                "datum": {
                    "type": "GeodeticReferenceFrame",
                    "name": "unknown",
                    "ellipsoid": {
                        "name": "unknown",
                        "radius": 3396000
                    },
                    "prime_meridian": {
                        "name": "Reference meridian",
                        "longitude": 0
                    }
                },
                "coordinate_system": {
                    "subtype": "ellipsoidal",
                    "axis": [
                        {
                            "name": "Longitude",
                            "abbreviation": "lon",
                            "direction": "east",
                            "unit": "degree"
                        },
                        {
                            "name": "Latitude",
                            "abbreviation": "lat",
                            "direction": "north",
                            "unit": "degree"
                        }
                    ]
                }
            },
            "conversion": {
                "name": "unknown",
                "method": {
                    "name": "Orthographic",
                    "id": {
                        "authority": "EPSG",
                        "code": 9840
                    }
                },
                "parameters": [
                    {
                        "name": "Latitude of natural origin",
                        "value": 7.61971,
                        "unit": "degree",
                        "id": {
                            "authority": "EPSG",
                            "code": 8801
                        }
                    },
                    {
                        "name": "Longitude of natural origin",
                        "value": 163.679,
                        "unit": "degree",
                        "id": {
                            "authority": "EPSG",
                            "code": 8802
                        }
                    },
                    {
                        "name": "False easting",
                        "value": 0,
                        "unit": "metre",
                        "id": {
                            "authority": "EPSG",
                            "code": 8806
                        }
                    },
                    {
                        "name": "False northing",
                        "value": 0,
                        "unit": "metre",
                        "id": {
                            "authority": "EPSG",
                            "code": 8807
                        }
                    }
                ]
            },
            "coordinate_system": {
                "subtype": "Cartesian",
                "axis": [
                    {
                        "name": "Easting",
                        "abbreviation": "E",
                        "direction": "east",
                        "unit": "metre"
                    },
                    {
                        "name": "Northing",
                        "abbreviation": "N",
                        "direction": "north",
                        "unit": "metre"
                    }
                ]
            }
        },
```

</details>

<details>
<summary>Passing PROJJSON w/ equirectangular projection</summary>

```
        "proj:projjson": {
            "$schema": "https://proj.org/schemas/v0.2/projjson.schema.json",
            "type": "ProjectedCRS",
            "name": "unknown",
            "base_crs": {
                "name": "unknown",
                "datum": {
                    "type": "GeodeticReferenceFrame",
                    "name": "unknown",
                    "ellipsoid": {
                        "name": "unknown",
                        "radius": 1560800
                    },
                    "prime_meridian": {
                        "name": "Reference meridian",
                        "longitude": 0
                    }
                },
                "coordinate_system": {
                    "subtype": "ellipsoidal",
                    "axis": [
                        {
                            "name": "Longitude",
                            "abbreviation": "lon",
                            "direction": "east",
                            "unit": "degree"
                        },
                        {
                            "name": "Latitude",
                            "abbreviation": "lat",
                            "direction": "north",
                            "unit": "degree"
                        }
                    ]
                }
            },
            "conversion": {
                "name": "unknown",
                "method": {
                    "name": "Equidistant Cylindrical (Spherical)",
                    "id": {
                        "authority": "EPSG",
                        "code": 1029
                    }
                },
                "parameters": [
                    {
                        "name": "Latitude of 1st standard parallel",
                        "value": 0,
                        "unit": "degree",
                        "id": {
                            "authority": "EPSG",
                            "code": 8823
                        }
                    },
                    {
                        "name": "Latitude of natural origin",
                        "value": 0,
                        "unit": "degree",
                        "id": {
                            "authority": "EPSG",
                            "code": 8801
                        }
                    },
                    {
                        "name": "Longitude of natural origin",
                        "value": 180,
                        "unit": "degree",
                        "id": {
                            "authority": "EPSG",
                            "code": 8802
                        }
                    },
                    {
                        "name": "False easting",
                        "value": 0,
                        "unit": "metre",
                        "id": {
                            "authority": "EPSG",
                            "code": 8806
                        }
                    },
                    {
                        "name": "False northing",
                        "value": 0,
                        "unit": "metre",
                        "id": {
                            "authority": "EPSG",
                            "code": 8807
                        }
                    }
                ]
            },
            "coordinate_system": {
                "subtype": "Cartesian",
                "axis": [
                    {
                        "name": "Easting",
                        "abbreviation": "E",
                        "direction": "east",
                        "unit": "metre"
                    },
                    {
                        "name": "Northing",
                        "abbreviation": "N",
                        "direction": "north",
                        "unit": "metre"
                    }
                ]
            }
        },
```

</details>

The orthographic project is a valid project (AFAIK) with the correct parameters defined. The string is being programmatically generated and passes validation on [staclint.com](http://staclint.com).

**Comment by demiurg** [comment]
Thanks for digging into this and finding the issue. Could you attach the full STAC item you are ingesting? It would help with testing the fix.

**Comment by jlaura** [comment]
I have had some time to look at this some more and test with a second dataset. Here is where I think the issue might be?

When I add a new collection via ingest, I see a new index is created in the ES instance with 10 fields mapped and a mapping type = `dynamic_templates,properties`. 

My stac item (that I later ingest) actually has something like 72 fields (depends on how many assets and what extensions). So, the index is incorrect because the existing index is based off of the column.

I am under the impression that I need to add the collection first, and then ingest the items. This is a standard deploy (as of 7/21 or so).

Question: When I ingest, should I go collection first and then items? If so, should the ingestion of the collection be creating an index with 10 items (and if so, how is that updated once an item is ingested?).

As always, many thanks to the maintainers on this project - it is amazing to be able to go from nothing to STAC compliant API so quickly.

**Comment by jlaura** [comment]
I have been able to get this working a bit more using dynamic mappings. Specifically, I manually define the mapping of just the geometry column as so:

```bash
mapping = {
        "dynamic_templates": [{
                "geo_shape": {
                    "match": "geometry",
                    "mapping": {
                        "type": "geo_shape"
                    }
                }
            }
        ]
    }
```

Then I can ingest as normal using the SNS/SQS queues provided by the project. This gets spatial queries enabled. Is this project using dynamic mappings to 'nudge' ES to set the proper types on the geometry fields?

I am just getting geometry to geo_shape, but I suspect centroid and perhaps bbox should also be geo_shape objects. 

The workaround workflow, in case anyone else is in the same position is to: (1) push the collection, (2) delete the collection, (3) re-add the collection using a HTTP PUT and then add a dynamic mapping (above) to the /my_collection/_mapping endpoint in ES, and finally (4) push all the data.
