### ISSUE TITLE
NoLivingConnectionsError when ingesting Item

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-server#152]
I tried to ingest an Item, and got this error. I waited a few minutes and tried again, and it worked. Could be related to an ongoing upgrade of ES? But other people seem to see this with the elasticsearch-js client also, so...

```
2022-02-17T20:03:36.452Z	18cb9c08-24aa-5528-92ba-c68088f95fe4	ERROR	NoLivingConnectionsError: Given the configuration, the ConnectionPool was not able to find a usable Connection for this request.
    at makeRequest (/var/task/index.js:16916:43)
    at Transport.request (/var/task/index.js:17172:7)
    at IndicesApi.indicesExistsApi [as exists] (/var/task/index.js:5367:25)
    at ElasticSearchWritableStream._write (/var/task/index.js:325:50)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at ElasticSearchWritableStream.Writable.write (internal/streams/writable.js:303:10)
    at DestroyableTransform.ondata (/var/task/index.js:36664:20)
    at DestroyableTransform.emit (events.js:400:28)
    at DestroyableTransform.emit (domain.js:475:12)
    at addChunk (/var/task/index.js:36281:12) {
  meta: undefined
}
```

**Comment by marchuffnagle** [comment]
I ran into this as well. I suspect there’s a connection leak in https://github.com/stac-utils/stac-server/blob/8db3ce65f983095c7f7d2b8697b3e0c844ff4f12/libs/ingest.js#L5

This should probably be a high priority.
